FROM apache/airflow:3.3.2

RUN pip install --no-cache-dir \
    faker \
    pandas \
    "pandera[pandas]" \
    "psycopg[binary]" \
    scikit-learn \
    xgboost \
    mlflow \
    fastapi \
    uvicorn \
    httpx